# Generated by Django 6.0.4 on 2026-04-10 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('riot_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('plaintext', models.TextField()),
                ('from_items', models.JSONField(default=list)),
                ('into_items', models.JSONField(default=list)),
                ('icon', models.URLField()),
                ('gold_base', models.IntegerField()),
                ('purchasable', models.BooleanField()),
                ('gold_total', models.IntegerField()),
                ('gold_sell', models.IntegerField()),
                ('tags', models.JSONField(default=list)),
                ('maps', models.JSONField(default=dict)),
                ('stats', models.JSONField(default=dict)),
                ('depth', models.IntegerField(null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
