# Generated by Django 6.0.4 on 2026-05-26 03:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_id', models.CharField(max_length=50, unique=True)),
                ('game_creation', models.BigIntegerField()),
                ('game_duration', models.IntegerField()),
                ('queue_id', models.IntegerField()),
                ('rank', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puuid', models.CharField(max_length=100, unique=True)),
                ('summoner_name', models.CharField(max_length=100, null=True)),
                ('platform', models.CharField(max_length=10)),
                ('tier', models.CharField(max_length=20, null=True)),
                ('division', models.CharField(max_length=5, null=True)),
                ('last_checked', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('champion', models.CharField(max_length=50)),
                ('win', models.BooleanField()),
                ('kills', models.IntegerField()),
                ('deaths', models.IntegerField()),
                ('assists', models.IntegerField()),
                ('item0', models.IntegerField(null=True)),
                ('item1', models.IntegerField(null=True)),
                ('item2', models.IntegerField(null=True)),
                ('item3', models.IntegerField(null=True)),
                ('item4', models.IntegerField(null=True)),
                ('item5', models.IntegerField(null=True)),
                ('item6', models.IntegerField(null=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matches.match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matches.player')),
            ],
        ),
    ]
