# Generated by Django 6.0.4 on 2026-05-26 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0003_remove_player_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='platform',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
