# Generated by Django 6.0.4 on 2026-05-26 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0004_add_match_platform'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='game_version',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
