# Generated by Django 6.0.4 on 2026-05-26 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0006_game_creation_to_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='game_creation',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='rank',
            field=models.CharField(db_index=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='champion',
            field=models.CharField(db_index=True, max_length=50),
        ),
    ]
