# Generated by Django 6.0.4 on 2026-10-10 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0009_add_core_build_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='champion',
            field=models.CharField(max_length=50),
        ),
        migrations.AddIndex(
            model_name='participant',
            index=models.Index(fields=['champion'], include=('win', 'core_build_order', 'match'), name='participant_champ_cover_idx'),
        ),
        # 0002's raw SQL dropped the indexes Django creates for these foreign
        # keys, but migration state still assumes they exist. Recreate them under
        # Django's own names so state and schema agree again.
        migrations.RunSQL(
            sql=[
                "CREATE INDEX IF NOT EXISTS matches_participant_match_id_1d4d653e ON matches_participant (match_id);",
                "CREATE INDEX IF NOT EXISTS matches_participant_puuid_a2ee47ed ON matches_participant (puuid);",
            ],
            reverse_sql=[
                "DROP INDEX IF EXISTS matches_participant_match_id_1d4d653e;",
                "DROP INDEX IF EXISTS matches_participant_puuid_a2ee47ed;",
            ],
        ),
    ]
